
package com.whitecitycode.aida;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AIDAWebServices", targetNamespace = "http://aida.dcsplus.net/ws/2010", wsdlLocation = "http://aida.eximtur.ro/tourOperator/ws/?wsdl")
public class AIDAWebServices
    extends Service
{

    private final static URL AIDAWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException AIDAWEBSERVICES_EXCEPTION;
    private final static QName AIDAWEBSERVICES_QNAME = new QName("http://aida.dcsplus.net/ws/2010", "AIDAWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aida.eximtur.ro/tourOperator/ws/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AIDAWEBSERVICES_WSDL_LOCATION = url;
        AIDAWEBSERVICES_EXCEPTION = e;
    }

    public AIDAWebServices() {
        super(__getWsdlLocation(), AIDAWEBSERVICES_QNAME);
    }

    public AIDAWebServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), AIDAWEBSERVICES_QNAME, features);
    }

    public AIDAWebServices(URL wsdlLocation) {
        super(wsdlLocation, AIDAWEBSERVICES_QNAME);
    }

    public AIDAWebServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AIDAWEBSERVICES_QNAME, features);
    }

    public AIDAWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AIDAWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AIDAWebServicesPT
     */
    @WebEndpoint(name = "AIDAWebServicesPT")
    public AIDAWebServicesPT getAIDAWebServicesPT() {
        return super.getPort(new QName("http://aida.dcsplus.net/ws/2010", "AIDAWebServicesPT"), AIDAWebServicesPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AIDAWebServicesPT
     */
    @WebEndpoint(name = "AIDAWebServicesPT")
    public AIDAWebServicesPT getAIDAWebServicesPT(WebServiceFeature... features) {
        return super.getPort(new QName("http://aida.dcsplus.net/ws/2010", "AIDAWebServicesPT"), AIDAWebServicesPT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AIDAWEBSERVICES_EXCEPTION!= null) {
            throw AIDAWEBSERVICES_EXCEPTION;
        }
        return AIDAWEBSERVICES_WSDL_LOCATION;
    }

}
