
package com.whitecitycode.aida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AIDAWebServicesPT", targetNamespace = "http://aida.dcsplus.net/ws/2010")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AIDAWebServicesPT {


    /**
     * Returns the requested list of codes.
     * 
     * @param codesListRQ
     * @return
     *     returns com.whitecitycode.aida.AIDACodesListRS
     */
    @WebMethod(operationName = "CodesList", action = "http://aida.dcsplus.net/ws/CodesList")
    @WebResult(name = "AIDA_CodesListRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "CodesListRS")
    public AIDACodesListRS codesList(
        @WebParam(name = "AIDA_CodesListRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "CodesListRQ")
        AIDACodesListRQ codesListRQ);

    /**
     * Returns the requested list of documents.
     * 
     * @param documentsListRQ
     * @return
     *     returns com.whitecitycode.aida.AIDADocumentsListRS
     */
    @WebMethod(operationName = "DocumentsList", action = "http://aida.dcsplus.net/ws/DocumentsList")
    @WebResult(name = "AIDA_DocumentsListRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "DocumentsListRS")
    public AIDADocumentsListRS documentsList(
        @WebParam(name = "AIDA_DocumentsListRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "DocumentsListRQ")
        AIDADocumentsListRQ documentsListRQ);

    /**
     * Returns the content of a requested document.
     * 
     * @param documentGetRQ
     * @return
     *     returns com.whitecitycode.aida.AIDADocumentGetRS
     */
    @WebMethod(operationName = "DocumentGet", action = "http://aida.dcsplus.net/ws/DocumentGet")
    @WebResult(name = "AIDA_DocumentGetRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "DocumentGetRS")
    public AIDADocumentGetRS documentGet(
        @WebParam(name = "AIDA_DocumentGetRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "DocumentGetRQ")
        AIDADocumentGetRQ documentGetRQ);

    /**
     * Returns the content of a requested document.
     * 
     * @param transferVehiclesRQ
     * @return
     *     returns com.whitecitycode.aida.AIDATransferVehiclesRS
     */
    @WebMethod(operationName = "TransferVehicles", action = "http://aida.dcsplus.net/ws/TransferVehicles")
    @WebResult(name = "AIDA_TransferVehiclesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferVehiclesRS")
    public AIDATransferVehiclesRS transferVehicles(
        @WebParam(name = "AIDA_TransferVehiclesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferVehiclesRQ")
        AIDATransferVehiclesRQ transferVehiclesRQ);

    /**
     * Gets the list of countries from the system.
     * 
     * @param globeCountriesRQ
     * @return
     *     returns com.whitecitycode.aida.AIDAGlobeCountriesRS
     */
    @WebMethod(operationName = "GlobeCountries", action = "http://aida.dcsplus.net/ws/GlobeCountries")
    @WebResult(name = "AIDA_GlobeCountriesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeCountriesRS")
    public AIDAGlobeCountriesRS globeCountries(
        @WebParam(name = "AIDA_GlobeCountriesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeCountriesRQ")
        AIDAGlobeCountriesRQ globeCountriesRQ);

    /**
     * Gets the list of regions from the system.
     * 
     * @param globeRegionsRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAGlobeRegionsRS
     */
    @WebMethod(operationName = "GlobeRegions", action = "http://aida.dcsplus.net/ws/GlobeRegions")
    @WebResult(name = "AIDA_GlobeRegionsRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeRegionsRS")
    public AIDAGlobeRegionsRS globeRegions(
        @WebParam(name = "AIDA_GlobeRegionsRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeRegionsRQ")
        AIDAGlobeRegionsRQ globeRegionsRQ);

    /**
     * Gets the list of counties from the system.
     * 
     * @param globeCountiesRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAGlobeCountiesRS
     */
    @WebMethod(operationName = "GlobeCounties", action = "http://aida.dcsplus.net/ws/GlobeCounties")
    @WebResult(name = "AIDA_GlobeCountiesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeCountiesRS")
    public AIDAGlobeCountiesRS globeCounties(
        @WebParam(name = "AIDA_GlobeCountiesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeCountiesRQ")
        AIDAGlobeCountiesRQ globeCountiesRQ);

    /**
     * Gets the list of cities from the system.
     * 
     * @param globeCitiesRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAGlobeCitiesRS
     */
    @WebMethod(operationName = "GlobeCities", action = "http://aida.dcsplus.net/ws/GlobeCities")
    @WebResult(name = "AIDA_GlobeCitiesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeCitiesRS")
    public AIDAGlobeCitiesRS globeCities(
        @WebParam(name = "AIDA_GlobeCitiesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeCitiesRQ")
        AIDAGlobeCitiesRQ globeCitiesRQ);

    /**
     * Gets the list of locations from the system.
     * 
     * @param globeLocationsRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAGlobeLocationsRS
     */
    @WebMethod(operationName = "GlobeLocations", action = "http://aida.dcsplus.net/ws/GlobeLocations")
    @WebResult(name = "AIDA_GlobeLocationsRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeLocationsRS")
    public AIDAGlobeLocationsRS globeLocations(
        @WebParam(name = "AIDA_GlobeLocationsRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GlobeLocationsRQ")
        AIDAGlobeLocationsRQ globeLocationsRQ);

    /**
     * Performs a request for information regarding the extra services included on a package entry
     * 
     * @param packExtraServicesRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAPackExtraServicesRS
     */
    @WebMethod(operationName = "PackExtraServices", action = "http://aida.dcsplus.net/ws/PackExtraServices")
    @WebResult(name = "AIDA_PackExtraServicesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackExtraServicesRS")
    public AIDAPackExtraServicesRS packExtraServices(
        @WebParam(name = "AIDA_PackExtraServicesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackExtraServicesRQ")
        AIDAPackExtraServicesRQ packExtraServicesRQ);

    /**
     * Performs a request for availability regarding a specific package and configuration
     * 
     * @param packAvailRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAPackAvailRS
     */
    @WebMethod(operationName = "PackAvail", action = "http://aida.dcsplus.net/ws/PackAvail")
    @WebResult(name = "AIDA_PackAvailRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackAvailRS")
    public AIDAPackAvailRS packAvail(
        @WebParam(name = "AIDA_PackAvailRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackAvailRQ")
        AIDAPackAvailRQ packAvailRQ);

    /**
     * Send complete information for all the segments in an itinerary
     * 
     * @param getItineraryFullRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAGetItineraryFullRS
     */
    @WebMethod(operationName = "GetItineraryFull", action = "http://aida.dcsplus.net/ws/GetItineraryFull")
    @WebResult(name = "AIDA_GetItineraryFullRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GetItineraryFullRS")
    public AIDAGetItineraryFullRS getItineraryFull(
        @WebParam(name = "AIDA_GetItineraryFullRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "GetItineraryFullRQ")
        AIDAGetItineraryFullRQ getItineraryFullRQ);

    /**
     * Performs a request for package booking
     * 
     * @param packBookRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAPackBookRS
     */
    @WebMethod(operationName = "PackBook", action = "http://aida.dcsplus.net/ws/PackBook")
    @WebResult(name = "AIDA_PackBookRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackBookRS")
    public AIDAPackBookRS packBook(
        @WebParam(name = "AIDA_PackBookRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackBookRQ")
        AIDAPackBookRQ packBookRQ);

    /**
     * Records a request for the packages catalog
     * 
     * @param packCatalogFileRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAPackCatalogFileRS
     */
    @WebMethod(operationName = "PackCatalogFile", action = "http://aida.dcsplus.net/ws/PackCatalogFile")
    @WebResult(name = "AIDA_PackCatalogFileRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackCatalogFileRS")
    public AIDAPackCatalogFileRS packCatalogFile(
        @WebParam(name = "AIDA_PackCatalogFileRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackCatalogFileRQ")
        AIDAPackCatalogFileRQ packCatalogFileRQ);

    /**
     * Performs a request for the packages details
     * 
     * @param packDetailsRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAPackDetailsRS
     */
    @WebMethod(operationName = "PackDetails", action = "http://aida.dcsplus.net/ws/PackDetails")
    @WebResult(name = "AIDA_PackDetailsRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackDetailsRS")
    public AIDAPackDetailsRS packDetails(
        @WebParam(name = "AIDA_PackDetailsRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "PackDetailsRQ")
        AIDAPackDetailsRQ packDetailsRQ);

    /**
     * Return transfer vehicles from AIDA system.
     * 
     * @param transferServiceVehiclesRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDATransferServiceVehiclesRS
     */
    @WebMethod(operationName = "TransferServiceVehicles", action = "http://aida.dcsplus.net/ws/TransferServiceVehicles")
    @WebResult(name = "AIDA_TransferServiceVehiclesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferServiceVehiclesRS")
    public AIDATransferServiceVehiclesRS transferServiceVehicles(
        @WebParam(name = "AIDA_TransferServiceVehiclesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferServiceVehiclesRQ")
        AIDATransferServiceVehiclesRQ transferServiceVehiclesRQ);

    /**
     * Performs a transfer search.
     * 
     * @param transferSearchRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDATransferSearchRS
     */
    @WebMethod(operationName = "TransferSearch", action = "http://aida.dcsplus.net/ws/TransferSearch")
    @WebResult(name = "AIDA_TransferSearchRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferSearchRS")
    public AIDATransferSearchRS transferSearch(
        @WebParam(name = "AIDA_TransferSearchRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferSearchRQ")
        AIDATransferSearchRQ transferSearchRQ);

    /**
     * Performs a transfer request for booking.
     * 
     * @param transferBookRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDATransferBookRS
     */
    @WebMethod(operationName = "TransferBook", action = "http://aida.dcsplus.net/ws/TransferBook")
    @WebResult(name = "AIDA_TransferBookRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferBookRS")
    public AIDATransferBookRS transferBook(
        @WebParam(name = "AIDA_TransferBookRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "TransferBookRQ")
        AIDATransferBookRQ transferBookRQ);

    /**
     * Returns the passsenger segments with their corresponding age limits for all accommodation services.
     * 
     * @param accServicePaxSegmentsRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccServicePaxSegmentsRS
     */
    @WebMethod(operationName = "AccServicePaxSegments", action = "http://aida.dcsplus.net/ws/AccServicePaxSegments")
    @WebResult(name = "AIDA_AccServicePaxSegmentsRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccServicePaxSegmentsRS")
    public AIDAAccServicePaxSegmentsRS accServicePaxSegments(
        @WebParam(name = "AIDA_AccServicePaxSegmentsRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccServicePaxSegmentsRQ")
        AIDAAccServicePaxSegmentsRQ accServicePaxSegmentsRQ);

    /**
     * Returns all existing units in the system with their details.
     * 
     * @param accUnitsRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccUnitsRS
     */
    @WebMethod(operationName = "AccUnits", action = "http://aida.dcsplus.net/ws/AccUnits")
    @WebResult(name = "AIDA_AccUnitsRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccUnitsRS")
    public AIDAAccUnitsRS accUnits(
        @WebParam(name = "AIDA_AccUnitsRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccUnitsRQ")
        AIDAAccUnitsRQ accUnitsRQ);

    /**
     * Returns all existing themes in the system with their details.
     * 
     * @param accThemesRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccThemesRS
     */
    @WebMethod(operationName = "AccThemes", action = "http://aida.dcsplus.net/ws/AccThemes")
    @WebResult(name = "AIDA_AccThemesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccThemesRS")
    public AIDAAccThemesRS accThemes(
        @WebParam(name = "AIDA_AccThemesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccThemesRQ")
        AIDAAccThemesRQ accThemesRQ);

    /**
     * Performs a search for accommodation services.
     * 
     * @param accSearchRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccSearchRS
     */
    @WebMethod(operationName = "AccSearch", action = "http://aida.dcsplus.net/ws/AccSearch")
    @WebResult(name = "AIDA_AccSearchRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccSearchRS")
    public AIDAAccSearchRS accSearch(
        @WebParam(name = "AIDA_AccSearchRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccSearchRQ")
        AIDAAccSearchRQ accSearchRQ);

    /**
     * Checks for availability and offers price and cancel penalties informationa search for accommodation services.
     * 
     * @param accAvailRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccAvailRS
     */
    @WebMethod(operationName = "AccAvail", action = "http://aida.dcsplus.net/ws/AccAvail")
    @WebResult(name = "AIDA_AccAvailRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccAvailRS")
    public AIDAAccAvailRS accAvail(
        @WebParam(name = "AIDA_AccAvailRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccAvailRQ")
        AIDAAccAvailRQ accAvailRQ);

    /**
     * Performs a reservation on an accommodation unit.
     * 
     * @param accBookRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccBookRS
     */
    @WebMethod(operationName = "AccBook", action = "http://aida.dcsplus.net/ws/AccBook")
    @WebResult(name = "AIDA_AccBookRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccBookRS")
    public AIDAAccBookRS accBook(
        @WebParam(name = "AIDA_AccBookRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccBookRQ")
        AIDAAccBookRQ accBookRQ);

    /**
     * Performs a search for accommodation services.
     * 
     * @param accSearchV2RQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccSearchV2RS
     */
    @WebMethod(operationName = "AccSearchV2", action = "http://aida.dcsplus.net/ws/AccSearchV2")
    @WebResult(name = "AIDA_AccSearchV2RS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccSearchV2RS")
    public AIDAAccSearchV2RS accSearchV2(
        @WebParam(name = "AIDA_AccSearchV2RQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccSearchV2RQ")
        AIDAAccSearchV2RQ accSearchV2RQ);

    /**
     * Gets extra services for an accommodation service.
     * 
     * @param accExtraServicesRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccExtraServicesRS
     */
    @WebMethod(operationName = "AccExtraServices", action = "http://aida.dcsplus.net/ws/AccExtraServices")
    @WebResult(name = "AIDA_AccExtraServicesRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccExtraServicesRS")
    public AIDAAccExtraServicesRS accExtraServices(
        @WebParam(name = "AIDA_AccExtraServicesRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccExtraServicesRQ")
        AIDAAccExtraServicesRQ accExtraServicesRQ);

    /**
     * Check services availability and offers price.
     * 
     * @param accAvailV2RQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccAvailV2RS
     */
    @WebMethod(operationName = "AccAvailV2", action = "http://aida.dcsplus.net/ws/AccAvailV2")
    @WebResult(name = "AIDA_AccAvailV2RS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccAvailV2RS")
    public AIDAAccAvailV2RS accAvailV2(
        @WebParam(name = "AIDA_AccAvailV2RQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccAvailV2RQ")
        AIDAAccAvailV2RQ accAvailV2RQ);

    /**
     * Performs a search for accommodation services.
     * 
     * @param accBookV2RQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAAccBookV2RS
     */
    @WebMethod(operationName = "AccBookV2", action = "http://aida.dcsplus.net/ws/AccBookV2")
    @WebResult(name = "AIDA_AccBookV2RS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccBookV2RS")
    public AIDAAccBookV2RS accBookV2(
        @WebParam(name = "AIDA_AccBookV2RQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "AccBookV2RQ")
        AIDAAccBookV2RQ accBookV2RQ);

    /**
     * Performs a search for extra services and activities.
     * 
     * @param extraServicesSearchRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAExtraServicesSearchRS
     */
    @WebMethod(operationName = "ExtraServicesSearch", action = "http://aida.dcsplus.net/ws/ExtraServicesSearch")
    @WebResult(name = "AIDA_ExtraServicesSearchRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ExtraServicesSearchRS")
    public AIDAExtraServicesSearchRS extraServicesSearch(
        @WebParam(name = "AIDA_ExtraServicesSearchRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ExtraServicesSearchRQ")
        AIDAExtraServicesSearchRQ extraServicesSearchRQ);

    /**
     * Performs an availability and price check for extra services and activities.
     * 
     * @param extraServicesAvailRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAExtraServicesAvailRS
     */
    @WebMethod(operationName = "ExtraServicesAvail", action = "http://aida.dcsplus.net/ws/ExtraServicesAvail")
    @WebResult(name = "AIDA_ExtraServicesAvailRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ExtraServicesAvailRS")
    public AIDAExtraServicesAvailRS extraServicesAvail(
        @WebParam(name = "AIDA_ExtraServicesAvailRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ExtraServicesAvailRQ")
        AIDAExtraServicesAvailRQ extraServicesAvailRQ);

    /**
     * Performs a booking of extra services or activities.
     * 
     * @param extraServicesBookRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAExtraServicesBookRS
     */
    @WebMethod(operationName = "ExtraServicesBook", action = "http://aida.dcsplus.net/ws/ExtraServicesBook")
    @WebResult(name = "AIDA_ExtraServicesBookRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ExtraServicesBookRS")
    public AIDAExtraServicesBookRS extraServicesBook(
        @WebParam(name = "AIDA_ExtraServicesBookRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ExtraServicesBookRQ")
        AIDAExtraServicesBookRQ extraServicesBookRQ);

    /**
     * Offers the details of a previously made reservation
     * 
     * @param reservationDetailsRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAReservationDetailsRS
     */
    @WebMethod(operationName = "ReservationDetails", action = "http://aida.dcsplus.net/ws/ReservationDetails")
    @WebResult(name = "AIDA_ReservationDetailsRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationDetailsRS")
    public AIDAReservationDetailsRS reservationDetails(
        @WebParam(name = "AIDA_ReservationDetailsRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationDetailsRQ")
        AIDAReservationDetailsRQ reservationDetailsRQ);

    /**
     * Performs a cancellation of a specified element.
     * 
     * @param reservationCancelRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAReservationCancelRS
     */
    @WebMethod(operationName = "ReservationCancel", action = "http://aida.dcsplus.net/ws/ReservationCancel")
    @WebResult(name = "AIDA_ReservationCancelRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationCancelRS")
    public AIDAReservationCancelRS reservationCancel(
        @WebParam(name = "AIDA_ReservationCancelRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationCancelRQ")
        AIDAReservationCancelRQ reservationCancelRQ);

    /**
     * Performs a cancellation of a specified element.
     * 
     * @param reservationRemarkAddRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAReservationRemarkAddRS
     */
    @WebMethod(operationName = "ReservationRemarkAdd", action = "http://aida.dcsplus.net/ws/ReservationRemarkAdd")
    @WebResult(name = "AIDA_ReservationRemarkAddRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationRemarkAddRS")
    public AIDAReservationRemarkAddRS reservationRemarkAdd(
        @WebParam(name = "AIDA_ReservationRemarkAddRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationRemarkAddRQ")
        AIDAReservationRemarkAddRQ reservationRemarkAddRQ);

    /**
     * Performs a cancellation of a specified element.
     * 
     * @param reservationRemarksListRQ
     * @return
     *     returns package com.whitecitycode.aida.AIDAReservationRemarksListRS
     */
    @WebMethod(operationName = "ReservationRemarksList", action = "http://aida.dcsplus.net/ws/ReservationRemarksList")
    @WebResult(name = "AIDA_ReservationRemarksListRS", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationRemarksListRS")
    public AIDAReservationRemarksListRS reservationRemarksList(
        @WebParam(name = "AIDA_ReservationRemarksListRQ", targetNamespace = "http://aida.dcsplus.net/ws/2010", partName = "ReservationRemarksListRQ")
        AIDAReservationRemarksListRQ reservationRemarksListRQ);

}
